travis:
  secure:
    BINSTAR_TOKEN: HW308xq+KJE1BRWwxwz+kGWUPY2oLx+RtCC8WmBwRBorj77GNApClSu0CHh1badgERYfU566LHUM6kIWak5dIfSPSrcr/fm1SfAxhP+yDhzUlssr2QD19gvQUI5vrMhvebGkrVvmshE0wZDLjuWUgelUpg+4595sHkUBmIhw2T2mvtPedwKLcx+Ll8c2Ty/zFYbittu/aLHTrvIW2UPYcavmSfn2wDxVUPzpGCaiXBW4h4abJmD89SJ8J9Vcp0ruBffTWq4zBDXNnrkT7Itf4nDvvwp3I8Q+cvqMaHxseeQIfCND6CaP1KS2bYrsky9X8MFo+V9/ZokXjhBt+WJegnH09Pw5//bSFqIhkLcAb43b+1ljTHYnwGMrjt7jK3FAFFmYw8M0AtmEnPpRyKxyj3GEd6KMu4Se8Y0VwRMKjz7ifu0E+aV65k8pvrVSHSOicDmabLWDvjHHgpY3kap1dS8hE9LyNuw58f69mCZhWMSk1gHo8Gd8kH5aLCUfWb61Ug5E1THJ3gTlc75uwBTIFEakpUO7QUFb3xe/7zQoJSXhoEkG87rB+5SeBoR1jvwjuUWMaMMmz+ct0d9qAA64/NXHNLrGd+UHRTkcqb6B80Vd7rU8KNQoowlCDgSIPU7bxQ4k5MV7JZSJgKFWMA77ToPFEAvgfoHWtYlaSdX98JU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
